server:
  port: 8080
spring:
  application:
    name: inditex
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  sql:
    init:
      mode: never # todo create local profile and add schema.sql and data.sql for script-based initialization. Create a test profile to disable script-base initialization.
  jpa:
    database: H2
    show-sql: true # log queries for development
    hibernate:
      ddl-auto: none # disable hibernate database initialization.