server:
  port: 8080
spring:
  application:
    name: inditex
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  # This property controls the execution of SQL scripts during application startup
  sql:
    init:
      mode: always # Always execute SQL scripts
  jpa:
    database: H2
    show-sql: true # log queries for development
    hibernate:
      ddl-auto: update # Hibernate should update the database schema based on the entity definitions
  # Enable H2 console to review data initialization
  h2:
    console:
      enabled: true